#!/bin/sh

# This should be run from the root of a branches/1.{9,10,11}.x working copy.

set -e

: ${SVN:=svn}

~/src/svn/site/tools/upcoming.py |
  {
    echo "<!-- Automatically generated by ^/subversion/site/tools/generate-upcoming-changes-log.sh -->"
    echo '<pre style="border-style: none">'
    ~/src/svn/site/tools/escape.py
    echo "</pre>"
  } > ~/src/svn/site/publish/upcoming.part.html

${SVN} commit ~/src/svn/site/publish/upcoming.part.html -m "* upcoming.part.html: Automatically regenerated"
