#!/bin/sh
# Search the given files/directories for URLs of messages in the haxx.se
# archives. Compile a list of <URL><TAB><MESSAGE-ID>.
#
# The output has been saved as 'publish/.message-ids.tsv'
#
# Message URLs are in this form:
#   https://svn.haxx.se/users/archive-2010-01/0001.shtml
#
# The message-id appears in the HTML source in this form:
#   <!-- id="69B68910-B4D0-428E-A4BB-FB7D6E87B24F_at_barrys-emacs.org" -->
#
# Note that '@' was transformed to '_at_', so we reverse that.
#
set -e
echo "# Message-ids of archived emails that are referenced by a svn.haxx.se URL."
echo "# Generated by $0 on `date +%Y-%m-%d`"
grep -hEro 'https?://svn.haxx.se/[a-z0-9-]*/archive-[0-9-]*/[0-9]*\.shtml' "$@" | sort | uniq | while read -r u; do
  printf '%s\t' "$u"; curl -sSf -L -- "$u" | perl -lne 's/<!-- id="(.*)" -->/\1/ and print s/_at_/@/gr and ++$printed; END { exit +($printed ? 0 : 1) }'
done
